### ISSUE TITLE
US county maps: city names are not shown anymore - Mapbox API responds with 403 forbidden

### ISSUE THREAD

**Issue by mberth** [obuchel/classification#15]
Currently, there are no city names on the map at https://www.endcoronavirus.org/us-counties.

The Mapbox API responds with 403 forbidden, so the terrain and streets layers cannot be loaded. 
My browser console shows:

- ajax.js:148 GET https://api.mapbox.com/v4/mapbox.mapbox-streets-v8,mapbox.mapbox-terrain-v2.json? ...  403 (Forbidden)
- ajax.js:132 GET https://api.mapbox.com/v4/mapbox.mapbox-terrain-v2,mapbox.mapbox-streets-v7.json? ... 403 (Forbidden)

Maybe the API key has expired?

The maps are still useable. 

Possible solutions:

- renew the API key
- add our own cities layer, with coordinates from some freely available GeoJson file

**Comment by obuchel** [comment]
I fixed it.
