### ISSUE TITLE
Add clipped version of county boundaries

### ISSUE THREAD

**Issue by speediedan** [obuchel/classification#9]
use https://www2.census.gov/geo/tiger/GENZ2019/shp/cb_2019_us_county_5m.zip, qgis to transform clipped boundaries file to geojson. Also move js code from embedded script to external js file for easier chrome devtools debugging.

**Comment by mberth** [comment]
Hey @speediedan -- can you give a little more explanation, please? What are clipped boundaries, why are they useful? 

I like having the javascript in a separate file. IMHO it would be good to split these two improvements into two pull requests. (Also: No need to write an issue for every pull request). 

Feel free to ping me on the endcoronavirus.org slack (I'm user `matthias` there)

**Comment by mberth** [comment]
I think classification_map3.html may be obsolete. @obuchel told me that classification_map.html and classification_map2.html are definitely used on the live website.

**Comment by speediedan** [comment]
nice to meet you digitally Matthias! Olga reached out to me to ask for a water clipped version of the county boundaries. [Before ](https://files.slack.com/files-pri/T2DRR8UNB-F014SU77G3C/image.png) [After](https://files.slack.com/files-pri/T2DRR8UNB-F014Z43LD36/image.png)
Good point on separating the js into a separate pr. I've been in the habit of having every PR address an "issue" but good to know that's not necessary for this project, thanks! I should have checked what the current active version of the html page was. 
![image2](https://user-images.githubusercontent.com/7462936/83684187-75050a80-a59b-11ea-84ed-ba07455df032.png)
![image3](https://user-images.githubusercontent.com/7462936/83684190-759da100-a59b-11ea-815b-e0d3add8cc25.png)

**Comment by speediedan** [comment]
btw, @obuchel still needs to do some more munging of the new json data to fully integrate it so I guess it might make sense to just let her edit this PR to drop the html changes and just use the updated/clipped geojson file. She's rockin through a ton of changes quickly, go Olga!

**Comment by speediedan** [comment]
per @mberth 's good suggestion, I'm going to close the [original PR](https://github.com/obuchel/classification/pull/10) and open separate PRs for the [county boundary changes](https://github.com/obuchel/classification/pull/11) and html changes.

**Comment by obuchel** [comment]
Thank you.
